### 2025년 06월 12일 SK 쉴더스 루키즈 파이썬 

In [ ]:
# 객체 지향 프로그래밍 : 객체의 개념을 프로그래밍에 도입
# 객체 : 변수들과 함수들로 구성 => 메모리에 올라가 있는 상태
# 클래스 : 변수들과 함수들이 어떻게 구성되는지의 설계도 -> 변수들을 정의, 함수들을 정의
# => 클래스만 정의했다 -> 사용 X, 클래스를 이용해서 객체로 만들어야 사용가능
# class 클래스 이름: 
#       변수와 함수들을 정의
# 객체 생성 => 변수 = 클래스 이름()
# 객체 활용 => 변수.객체가 가지는 변수 / 변수.메서드()   메서드: 객체가 가지는 함수

In [6]:
# 클래스 정의
class Cookie:
    pass

# 객체 생성
c1 = Cookie()
c2 = Cookie()

print(id(c1), type(c1))
print(id(c2), type(c2))

2020222975152 <class '__main__.Cookie'>
2020222675024 <class '__main__.Cookie'>


In [19]:
# 사칙연산을 하는 클래스 정의: 클래스 이름, 변수, 함수
# 변수는 두개, 함수(메서드) 4개

class FourCal:
    
    # 초기화(변수 선언 -> 최초 데이터를 할당) 메서드
    # 필요한 변수들의 생성, 값을 초기화
    def __init__(self, first, second): # 초기화 메서드
        self.first = first
        self.second = second

    # 클래스에서 함수를 정의할 때에는 반드시 self 매개변수를 받아야한다.
    # self = 객체 자신을 가리키는 변수
    def setdata(self, first, second):
        self.first = first
        self.second = second
    
    # 사칙 연산 함수들들
    def add(self):
        return self.first + self.second
    
    def sub(self):
        return self.first - self.second
    
    def mul(self):
        return self.first * self.second
    
    def div(self):
        return self.first / self.second


# cal_1 = FourCal()
# type(cal_1)
# cal_1.setdata(10,20)
# print(cal_1.first, cal_1.second)

# cal_2 = FourCal(10, 20)
# print(cal_2.first, cal_2.second)

cal_3 = FourCal(10, 3)
print(cal_3.first, cal_3.second)
print(cal_3.add(), cal_3.sub(), cal_3.mul(), cal_3.div())





10 3
13 7 30 3.3333333333333335


In [26]:
# 학생 class 생성 -> 객체 생성
# 학생: 학번, 이름, 국어점수, 영어점수, 수학점수
# 기능: 전체 데이터 출력하는 메서드 (이름, 학번, 총점, 평균균)
#       총점 계산 메서드
#       평균 계산 메서드
# 시뮬레이션: 테스트 학생 데이터 생성 -> 결과 출력력

class Student:
    def __init__(self, name, sno, kor, eng, math):
        self.name = name
        self.sno = sno
        self.kor = kor
        self.eng = eng
        self.math = math

    def total_score(self):
        return self.kor + self.eng + self.math
    
    def avg_score(self):
        return (self.kor + self.eng + self.math) / 3
    
    def print_all(self):
        result = [self.name, self.sno, self.total_score(), self.avg_score()]
        return result
    def print_result(self):
        print('성적표', '-' * 20)
        print(f'이름 : {self.name} ({self.sno})')
        print('국어: ', self.kor)
        print('영어: ', self.eng)
        print('수학: ', self.math)
        print('총점: ', self.total_score())
        print('평균: ', self.avg_score())

student1 = Student('홍길동', 123, 100, 90, 80)
student1.print_all()
student1.print_result()
   

성적표 --------------------
이름 : 홍길동 (123)
국어:  100
영어:  90
수학:  80
총점:  270
평균:  90.0


In [30]:
students = [
    Student('홍길동1', 1234, 100, 90, 80),
    Student('홍길동2', 1235, 100, 90, 80),
    Student('홍길동3', 1236, 100, 90, 80),
    Student('홍길동4', 1237, 100, 90, 80),
    Student('홍길동5', 1238, 100, 90, 80),
]

for s in students :
    s.print_result()

성적표 --------------------
이름 : 홍길동1 (1234)
국어:  100
영어:  90
수학:  80
총점:  270
평균:  90.0
성적표 --------------------
이름 : 홍길동2 (1235)
국어:  100
영어:  90
수학:  80
총점:  270
평균:  90.0
성적표 --------------------
이름 : 홍길동3 (1236)
국어:  100
영어:  90
수학:  80
총점:  270
평균:  90.0
성적표 --------------------
이름 : 홍길동4 (1237)
국어:  100
영어:  90
수학:  80
총점:  270
평균:  90.0
성적표 --------------------
이름 : 홍길동5 (1238)
국어:  100
영어:  90
수학:  80
총점:  270
평균:  90.0


In [ ]:
# 클래스 상속: 새로운 클래스를 만들 때 기존의 클래스의 멤버들을 받아서 생성하는 방법
# class 클래스 이름(부모 클래스)
class MoreFourCal(FourCal) :
    def pow(self):
        return self.first** self.second # first의 second 승(제곱 의 계산)
    
    def div(self):
        if self.second == 0 :
            return 0
        else: 
            return self.first / self.second

mcal_1 = MoreFourCal(100,0)
print(mcal_1.add())
print(mcal_1.div())
print(mcal_1.pow())

100
0
1


In [7]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr, type(arr))
arr + 10

[1 2 3 4 5] <class 'numpy.ndarray'>


array([11, 12, 13, 14, 15])

In [11]:
# 배열의 생성
# 0 으로 채워지는 배열 생성

zeros = np.zeros((1,3))
print(zeros)

[[0. 0. 0.]]


In [16]:
# 1로 채워지는 배열
ones = np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [18]:
# 일련번호 생성되는 배열
# 0~ 10 사이의 숫자를 2씩 간격으로 생성
seq_1 = np.arange(0, 10, 2)
print(seq_1)

[0 2 4 6 8]


In [22]:
# 지정된 범위 안에서 동일한 간격으로 숫자를 생성
# 0~1 5개로 구분

linspace = np.linspace(1, 10, 4)
print(linspace)

[ 1.  4.  7. 10.]


In [ ]:
# 배열의 속성 확인
arr1 = np.array([[1,2,3], [4,5,6],[7,8,9]])
print(type(arr1)) # 넘파이 배열
print(arr1.shape) # 배열의 크기 (행, 열)
print(arr1.ndim) # 배열의 차원
print(arr1.size) # 요소의 개수
print(arr1.dtype) # int64 배열 원소의 데이터 타입


<class 'numpy.ndarray'>
(3, 3)
2
9
int64
